version: '3'
services: 
    server:
        build: .
        expose: 
            - 3000
        environment: 
            API_HOST: 3000
            APP_SERVER_PORT: 3000
        ports: 
            - 3000:3000         
        command: node server
    client:
            build: ./client
            environment: 
                - 3001=3001
            expose:
                - 3001    
            ports: 
                - 3001:3000
            links:
                - server
            command: npm start   