version: "3"
services: 
    server:
        container_name: Server
        build: .
        image: test/server
        expose: 
            - 3000
        environment: 
            API_HOST: 3000
            APP_SERVER_PORT: 3000
        ports: 
            - 3000:3000         
        command: node server
    client:
            container_name: Clienti
            build:
                context: ./client
                dockerfile: Dockerfile    
            image: test2/clienti    
            environment: 
                APP_CLIENT_PORT: 3002
            expose:
                - 3002    
            ports: 
                - "3002:3000"
            command: npm start 
            links:
                - server
   
                